#!/bin/bash

APP_NAME="InfoTVConfigurator"

calc_wt_size() {
    # NOTE: it's tempting to redirect stderr to /dev/null, so supress error
    # output from	tput. However in this case, tput detects neither stdout or		
    # stderr is a tty and so only gives default 80, 24 values
    WT_HEIGHT=18
    WT_WIDTH=$(tput cols)
    
    if [ -z "$WT_WIDTH" ] || [ "$WT_WIDTH" -lt 60 ]; then
	WT_WIDTH=80
    fi
    if [ "$WT_WIDTH" -gt 178 ]; then
	WT_WIDTH=120
    fi
    WT_MENU_HEIGHT=$((WT_HEIGHT - 7))
}

do_about() {
    whiptail --msgbox "\
This tool is for configuration of DemoInfoTV application
" 20 70 1
    return 0
}

do_exit() {
    exit 1
}

##
# Interactive stuff
#

calc_wt_size


while true; do
    FUN=$(whiptail --title "${APP_NAME} Configurator Utility" \
		   --menu	"Setup Options" $WT_HEIGHT $WT_WIDTH $WT_MENU_HEIGHT \
		   --cancel-button Finish \
		   --ok-button Select \
		   "1 Database config" "Configure database connection" \
		   "2 Page config" "Configure enabled pages" \
		   "9 About configurator" "Information about this configuration tool" \
		   "0 Exit" "Quit configuration utility" \
		   3>&1 1>&2 2>&3)
    
    RET=$?

    if [ $RET -eq 1 ]; then
	do_exit
    elif [ $RET -eq 0 ]; then
	case "$FUN" in
	    1\ *) do_db_config ;;
	    2\ *) do_page_config ;;
	    9\ *) do_about ;;
	    0\ *) do_exit ;;
	    *) whiptail --msgbox "Program error: unregognized option" 20 60 1 ;;
	esac || whiptail --msgbox "There was an error running option $FUN" 20 60 1
    else
	exit 1
    fi

done





