#!/bin/bash

# define default values
APPNAME="InfoTVConfigurator"
INTERACTIVE=True
ORIENTATION="Landscape"
WT_HEIGHT=18
REGURL="http://localhost/demoinfo/server/register.php"
LOGFILE="/tmp/demoinfo-app.log"
CLIENTID=$(hostid)
REFRESH_TIME=30

if [ -f .env ]; then
    source .env
    CURRENT_DBHOST=$DBHOST
    CURRENT_DBPORT=$DBPORT
    CURRENT_DBNAME=$DBNAME
    CURRENT_DBUSER=$DBUSER
    CURRENT_DBPASS=$DBPASS
fi

calc_wt_size() {
    # NOTE: it's tempting to redirect stderr to /dev/null, so supress error
    # output from	tput. However in this case, tput detects neither stdout or		
    # stderr is a tty and so only gives default 80, 24 values
    WT_HEIGHT=18
    WT_WIDTH=$(tput cols)
    
    if [ -z "$WT_WIDTH" ] || [ "$WT_WIDTH" -lt 60 ]; then
	WT_WIDTH=80
    fi
    if [ "$WT_WIDTH" -gt 178 ]; then
	WT_WIDTH=120
    fi
    WT_MENU_HEIGHT=$((WT_HEIGHT - 7))
}

do_about() {
    whiptail --msgbox "\
This tool is for configuration of DemoInfoTV application
" 20 70 1
    return 0
}

do_exit() {
    cat > .env << _EOF_
# Application Info
APPNAME="$APPNAME"
CLIENTID="$CLIENTID"
REGURL="$REGURL"
REFRESH_TIME="$REFRESH_TIME"

# Database configuration
DBHOST="$CURRENT_DBHOST"
DBPORT="$CURRENT_DBPORT"
DBNAME="$CURRENT_DBNAME"
DBUSER="$CURRENT_DBUSER"
DBPASS="$CURRENT_DBPASS"

# Display orientation   "Landscape" | "Portrait"
ORIENTATION="$ORIENTATION"

# Use Crontab
CRONTAB="$CRONTAB"

# end-of-config-file
_EOF_
    exit 1
}

do_crontab() {
    whiptail --yesno "Enable Crontab?" $CRONTAB 20 60 2
    RET=$?
    if [ $RET -eq 0 ]; then
	# yes
	CRONTAB="yes"
    elif [ $RET -eq 1 ]; then
	# no
	CRONTAB="no"
    else
	return $RET
    fi	
}

do_orientation() {
    case "$ORIENTATION" in
	"Landscape")
	    LANDON="ON"
	    PORTON="OFF"
	    ;;
	"Portrait")
	    LANDON="OFF"
	    PORTON="ON"
	    ;;
	*)
	    LANDON="ON"
	    PORTON="OFF"
    esac
    
    if [ "$INTERACTIVE" = True ]; then
	ORIENTATION=$(whiptail --radiolist "Display orientation:" 20 60 2 \
					"Landscape" "" "$LANDON" \
					"Portrait" "" "$PORTON" \
					3>&1 1>&2 2>&3)
    else
	ORIENTATION="$1"
	true
    fi
}

do_register() {
    if [ "$INTERACTIVE" = True ]; then
	NEW_REGISTRY=$(whiptail --inputbox "Registry service URL path:" 20 60 "$REGURL" 3>&1 1>&2 2>&3)
    else
	NEW_REGISTRY="$1"
    fi
    REGURL="$NEW_REGISTRY"
}

do_page_config() {
    whiptail --msgbox "Not yet implemented" 20 60
}

do_logfile() {
    if [ "$INTERACTIVE" = True ]; then
	NEW_LOGFILE=$(whiptail --inputbox "Logfile to be used:" 20 60 "$LOGFILE" 3>&1 1>&2 2>&3)
    else
	NEW_LOGFILE="$1"
    fi
    LOGFILE="$NEW_LOGFILE"
}

do_db_config() {
    if [ "$INTERACTIVE" = True ]; then
	NEW_DBHOST=$(whiptail --inputbox "Database server host:" 20 60 "$CURRENT_DBHOST" 3>&1 1>&2 2>&3)
    else
	NEW_DBHOST="$1"
	true
    fi
    
    if [ "$INTERACTIVE" = True ]; then
	NEW_DBPORT=$(whiptail --inputbox "Database port:" 20 60 "$CURRENT_DBPORT" 3>&1 1>&2 2>&3)
    else
	NEW_DBPORT="$1"
	true
    fi

    if [ "$INTERACTIVE" = True ]; then
	NEW_DBNAME=$(whiptail --inputbox "Database name:" 20 60 "$CURRENT_DBNAME" 3>&1 1>&2 2>&3)
    else
	NEW_DBNAME="$1"
	true
    fi

    if [ "$INTERACTIVE" = True ]; then
	NEW_DBUSER=$(whiptail --inputbox "Database username:" 20 60 "$CURRENT_DBUSER" 3>&1 1>&2 2>&3)
    else
	NEW_DBUSER="$1"
	true
    fi

    if [ "$INTERACTIVE" = True ]; then
	NEW_DBPASS=$(whiptail --passwordbox "Database password:" 20 60 "$CURRENT_DBPASS" 3>&1 1>&2 2>&3)
    else
	NEW_DBPASS="$1"
	true
    fi
    
    CURRENT_DBPORT=$NEW_DBPORT
    CURRENT_DBHOST=$NEW_DBHOST
    CURRENT_DBNAME=$NEW_DBNAME
    CURRENT_DBUSER=$NEW_DBUSER
    CURRENT_DBPASS=$NEW_DBPASS
}

##
# Interactive stuff
#

calc_wt_size


while true; do
    FUN=$(whiptail --title "${APPNAME} Configurator Utility" \
		   --menu	"Setup Options" $WT_HEIGHT $WT_WIDTH $WT_MENU_HEIGHT \
		   --cancel-button Finish \
		   --ok-button Select \
		   "1 Database config" "Configure database connection" \
		   "2 Page config" "Configure enabled pages" \
		   "3 Display orientation" "Set display orientation" \
		   "4 Use Crontab Scheduling" "Enable or disable crontab scheduling" \
		   "5 Set registry server" "Set the IP/name of registry server" \
		   "9 About configurator" "Information about this configuration tool" \
		   "0 Exit" "Quit configuration utility and write new configuration" \
		   3>&1 1>&2 2>&3)
    
    RET=$?

    if [ $RET -eq 1 ]; then
	do_exit
    elif [ $RET -eq 0 ]; then
	case "$FUN" in
	    1\ *) do_db_config ;;
	    2\ *) do_page_config ;;
	    3\ *) do_orientation ;;
	    4\ *) do_crontab ;;
	    5\ *) do_register ;;
	    9\ *) do_about ;;
	    0\ *) do_exit ;;
	    *) whiptail --msgbox "Program error: unregognized option" 20 60 1 ;;
	esac || whiptail --msgbox "There was an error running option $FUN" 20 60 1
    else
	exit 1
    fi

done





