#!/bin/bash

APP_NAME="InfoTVConfigurator"
INTERACTIVE=True
DISPLAY_ORIENTATION="Landscape"
WT_HEIGHT=18
REGISTER_URL="http://localhost/demoinfo/server/register.php"

if [ -f .env ]; then
    source .env
    CURRENT_DBHOST=$DB_HOST
    CURRENT_DBPORT=$DB_PORT
    CURRENT_DBNAME=$DB_NAME
    CURRENT_DBUSER=$DB_USER
    CURRENT_DBPASS=$DB_PASS
fi

calc_wt_size() {
    # NOTE: it's tempting to redirect stderr to /dev/null, so supress error
    # output from	tput. However in this case, tput detects neither stdout or		
    # stderr is a tty and so only gives default 80, 24 values
    WT_HEIGHT=18
    WT_WIDTH=$(tput cols)
    
    if [ -z "$WT_WIDTH" ] || [ "$WT_WIDTH" -lt 60 ]; then
	WT_WIDTH=80
    fi
    if [ "$WT_WIDTH" -gt 178 ]; then
	WT_WIDTH=120
    fi
    WT_MENU_HEIGHT=$((WT_HEIGHT - 7))
}

do_about() {
    whiptail --msgbox "\
This tool is for configuration of DemoInfoTV application
" 20 70 1
    return 0
}

do_exit() {
    cat > .env << _EOF_
# Database configuration
DB_HOST="$CURRENT_DBHOST"
DB_PORT="$CURRENT_DBPORT"
DB_NAME="$CURRENT_DBNAME"
DB_USER="$CURRENT_DBUSER"
DB_PASS="$CURRENT_DBPASS"
# Display orientation   "Landscape" | "Portrait"
DISPLAY_ORIENTATION="$DISPLAY_ORIENTATION"
# Use Crontab
SCHEDULE_CRONTAB="$SCHEDULE_CRONTAB"
# Registry service
REGISTER_URL="$REGISTER_URL"
_EOF_
    exit 1
}

do_crontab() {
    whiptail --yesno "Enable Crontab?" $USECRONTAB 20 60 2
    RET=$?
    if [ $RET -eq 0 ]; then
	# yes
	SCHEDULE_CRONTAB="yes"
    elif [ $RET -eq 1 ]; then
	# no
	SCHEDULE_CRONTAB="no"
    else
	return $RET
    fi	
}

do_orientation() {
    case "$DISPLAY_ORIENTATION" in
	"Landscape")
	    LANDON="ON"
	    PORTON="OFF"
	    ;;
	"Portrait")
	    LANDON="OFF"
	    PORTON="ON"
	    ;;
	*)
	    LANDON="ON"
	    PORTON="OFF"
    esac
    
    if [ "$INTERACTIVE" = True ]; then
	DISPLAY_ORIENTATION=$(whiptail --radiolist "Display orientation:" 20 60 2 \
				       "Landscape" "" "$LANDON" \
				       "Portrait" "" "$PORTON" \
				       3>&1 1>&2 2>&3)
    else
	DISPLAY_ORIENTATION="$1"
	true
    fi
}

do_register() {
    if [ "$INTERACTIVE" = True ]; then
	NEW_REGISTRY=$(whiptail --inputbox "Registry service URL path:" 20 60 "$REGISTER_URL" 3>&1 1>&2 2>&3)
    else
	NEW_REGISTRY="$1"
    fi
    REGISTER_URL="$NEW_REGISTRY"
}

do_db_config() {
    if [ "$INTERACTIVE" = True ]; then
	NEW_DBHOST=$(whiptail --inputbox "Database server host:" 20 60 "$CURRENT_DBHOST" 3>&1 1>&2 2>&3)
    else
	NEW_DBHOST="$1"
	true
    fi
    
    if [ "$INTERACTIVE" = True ]; then
	NEW_DBPORT=$(whiptail --inputbox "Database port:" 20 60 "$CURRENT_DBPORT" 3>&1 1>&2 2>&3)
    else
	NEW_DBPORT="$1"
	true
    fi

    if [ "$INTERACTIVE" = True ]; then
	NEW_DBNAME=$(whiptail --inputbox "Database name:" 20 60 "$CURRENT_DBNAME" 3>&1 1>&2 2>&3)
    else
	NEW_DBNAME="$1"
	true
    fi

    if [ "$INTERACTIVE" = True ]; then
	NEW_DBUSER=$(whiptail --inputbox "Database username:" 20 60 "$CURRENT_DBUSER" 3>&1 1>&2 2>&3)
    else
	NEW_DBUSER="$1"
	true
    fi

    if [ "$INTERACTIVE" = True ]; then
	NEW_DBPASS=$(whiptail --passwordbox "Database password:" 20 60 "$CURRENT_DBPASS" 3>&1 1>&2 2>&3)
    else
	NEW_DBPASS="$1"
	true
    fi
    
    CURRENT_DBPORT=$NEW_DBPORT
    CURRENT_DBHOST=$NEW_DBHOST
    CURRENT_DBNAME=$NEW_DBNAME
    CURRENT_DBUSER=$NEW_DBUSER
    CURRENT_DBPASS=$NEW_DBPASS
}

##
# Interactive stuff
#

calc_wt_size


while true; do
    FUN=$(whiptail --title "${APP_NAME} Configurator Utility" \
		   --menu	"Setup Options" $WT_HEIGHT $WT_WIDTH $WT_MENU_HEIGHT \
		   --cancel-button Finish \
		   --ok-button Select \
		   "1 Database config" "Configure database connection" \
		   "2 Page config" "Configure enabled pages" \
		   "3 Display orientation" "Set display orientation" \
		   "4 Use Crontab Scheduling" "Enable or disable crontab scheduling" \
		   "5 Set registry server" "Set the IP/name of registry server" \
		   "9 About configurator" "Information about this configuration tool" \
		   "0 Exit" "Quit configuration utility and write new configuration" \
		   3>&1 1>&2 2>&3)
    
    RET=$?

    if [ $RET -eq 1 ]; then
	do_exit
    elif [ $RET -eq 0 ]; then
	case "$FUN" in
	    1\ *) do_db_config ;;
	    2\ *) do_page_config ;;
	    3\ *) do_orientation ;;
	    4\ *) do_crontab ;;
	    5\ *) do_register ;;
	    9\ *) do_about ;;
	    0\ *) do_exit ;;
	    *) whiptail --msgbox "Program error: unregognized option" 20 60 1 ;;
	esac || whiptail --msgbox "There was an error running option $FUN" 20 60 1
    else
	exit 1
    fi

done





